Automate quick start steps in setup.sh and teardown.sh
Boostport/kubernetes-vault pull request #35
Opened 2017-05-04 22:07 UTC by JulianWei

2017-05-04 22:34 UTC, F21 requested changes
Looks great! Can you please squash your commits? I'll try it out later today or tomorrow and merge if it's all good 😄

2017-05-04 22:34 UTC, F21 commented on deployments/quick-start/setup.sh
> +
Only 1 new line here.

2017-05-04 22:34 UTC, F21 commented on deployments/quick-start/setup.sh
> +
Only 1 new line here.

2017-05-04 22:34 UTC, F21 commented on deployments/quick-start/setup.sh
> +
Remove the extra new lines.

2017-05-04 22:34 UTC, F21 commented on deployments/quick-start/kubernetes-vault.yaml
> +            name: kubernetes-vault
Please rebase against master as the changes to this file is not necessary.

2017-05-05 09:32 UTC, F21 commented on deployments/quick-start/kubernetes-vault.yaml
> +            name: kubernetes-vault
Can you exclude the change to this file?

2017-05-05 17:13 UTC, JulianWei commented
I updated my pull request, please take a look.

2017-05-06 01:19 UTC, F21 commented
Thanks! 👍 I'll spin up a minikube cluster today or tomorrow to test it out.

2017-05-06 07:50 UTC, F21 commented
@JulianWei I just tested out the setup and teardown scripts and they work great! 

However, I am seeing this error (it does not negatively affect the setup, but it would still be good to fix).

See the complete log:
```
$ ./setup.sh
service "vault" created
deployment "vault" created
Vault pod name: vault-3485173613-05575
wait 1 second for Vault up and running
./setup.sh: 39: ./setup.sh: maxWaitSecond--: not found <---------------------
Vault pod status Running
nohup: appending output to 'nohup.out'
Successfully authenticated! You are now logged in.
token: vault-root-token
token_duration: 0
token_policies: [root]
Successfully mounted 'pki' at 'root-ca'!
Key             Value
---             -----
certificate     -----BEGIN CERTIFICATE-----
MIIC9DCCAdygAwIBAgIUW0MogXyKdy0r29DKboKCCg0eeg0wDQYJKoZIhvcNAQEL
BQAwEjEQMA4GA1UEAxMHUm9vdCBDQTAeFw0xNzA1MDYwNzQwMjRaFw0yNzA1MDQw
NzQwNTRaMBIxEDAOBgNVBAMTB1Jvb3QgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
DwAwggEKAoIBAQDz8suif4i/oNsP7p2HGyukW3IosdRDeUg980OcD6lSBJsLrBCB
8U70voxcUyX6JOrXXLFirEs5tjS2VJ9KPB0vQCUERqmPHJBP/Wa33YU9KhLA7yJt
tFYVEVpXa+UCWcWoB917Qgp2iLK6FTs0PfqHfjHTisVcVPw4Ueil7IvdIZdsweOg
0EHQutW5VSKPwipSHTzShDhoW6DoRO6J4webXt/Z2Eg+feKnLk3lOvwVOicAbtwj
a9IKsmLpe4PR0lSltXnFVAwvRicopQLy95bIOxMDHrfgFxOlJZjAt/Sg1ASdhnmV
fhfBbNumIyxBEmJiKGgIJ0xI2iMocYIzYWwzAgMBAAGjQjBAMA4GA1UdDwEB/wQE
AwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRhCgLqs0hmJphE4Ptg94OQ
np2aJzANBgkqhkiG9w0BAQsFAAOCAQEA77zCYv2jhS9rWsWJcFjIitHN6SsLqIeU
c8yC3YG7ThKiWgc/rrxiL76YVYCfQKOi2xwqFqHryFnWK66rGksnyPo32lYB5Eaq
9tckju2LZCtqSHnhJ4lgK/iyyYJg+CqfPqT2LMv9QYWcMhYHdT54mwbShRQdR5u4
vUFcq1ZQrDfLBdXwCil46+Q9liycsUEJbT8Z8ya7uHXGAuBPdec8gscjIZaGwjH+
RnEa4zZSkf2ZHRLzWeiP+meGVm0Ks7gCaFTtvFQiC2/DIJMlr6hndnYIH2UzpsYw
MjwC8KcaC7KnZi0UqZ76hX4Sx26TtCc5hA5gWdMIrSE5ZxNORPE0qg==
-----END CERTIFICATE-----
expiration      1809416454
issuing_ca      -----BEGIN CERTIFICATE-----
MIIC9DCCAdygAwIBAgIUW0MogXyKdy0r29DKboKCCg0eeg0wDQYJKoZIhvcNAQEL
BQAwEjEQMA4GA1UEAxMHUm9vdCBDQTAeFw0xNzA1MDYwNzQwMjRaFw0yNzA1MDQw
NzQwNTRaMBIxEDAOBgNVBAMTB1Jvb3QgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
DwAwggEKAoIBAQDz8suif4i/oNsP7p2HGyukW3IosdRDeUg980OcD6lSBJsLrBCB
8U70voxcUyX6JOrXXLFirEs5tjS2VJ9KPB0vQCUERqmPHJBP/Wa33YU9KhLA7yJt
tFYVEVpXa+UCWcWoB917Qgp2iLK6FTs0PfqHfjHTisVcVPw4Ueil7IvdIZdsweOg
0EHQutW5VSKPwipSHTzShDhoW6DoRO6J4webXt/Z2Eg+feKnLk3lOvwVOicAbtwj
a9IKsmLpe4PR0lSltXnFVAwvRicopQLy95bIOxMDHrfgFxOlJZjAt/Sg1ASdhnmV
fhfBbNumIyxBEmJiKGgIJ0xI2iMocYIzYWwzAgMBAAGjQjBAMA4GA1UdDwEB/wQE
AwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRhCgLqs0hmJphE4Ptg94OQ
np2aJzANBgkqhkiG9w0BAQsFAAOCAQEA77zCYv2jhS9rWsWJcFjIitHN6SsLqIeU
c8yC3YG7ThKiWgc/rrxiL76YVYCfQKOi2xwqFqHryFnWK66rGksnyPo32lYB5Eaq
9tckju2LZCtqSHnhJ4lgK/iyyYJg+CqfPqT2LMv9QYWcMhYHdT54mwbShRQdR5u4
vUFcq1ZQrDfLBdXwCil46+Q9liycsUEJbT8Z8ya7uHXGAuBPdec8gscjIZaGwjH+
RnEa4zZSkf2ZHRLzWeiP+meGVm0Ks7gCaFTtvFQiC2/DIJMlr6hndnYIH2UzpsYw
MjwC8KcaC7KnZi0UqZ76hX4Sx26TtCc5hA5gWdMIrSE5ZxNORPE0qg==
-----END CERTIFICATE-----
serial_number   5b:43:28:81:7c:8a:77:2d:2b:db:d0:ca:6e:82:82:0a:0d:1e:7a:0d

Success! Data written to: root-ca/config/urls
Successfully mounted 'pki' at 'intermediate-ca'!
Success! Data written to: intermediate-ca/intermediate/set-signed
Success! Data written to: intermediate-ca/config/urls
Success! Data written to: intermediate-ca/roles/kubernetes-vault
Successfully enabled 'approle' at 'approle'!
Success! Data written to: auth/approle/role/sample-app
Policy 'kubernetes-vault' written.
Success! Data written to: auth/token/roles/kubernetes-vault
service "kubernetes-vault" created
configmap "kubernetes-vault" created
deployment "kubernetes-vault" created
deployment "sample-app" created
View the logs using the Kubernetes dashboard or kubectl logs mypod and confirm that each pod receive a token. The token and various other information related to the token should be logged.
```

Another concern of mine is that we are only waiting for 5 seconds for the Vault image to download and deploy.

Since the Vault image is around 67MB, I suggest what we increase the timeout for download/deploy to 10 minutes, so that it can have enough time to download over slow connections.

2017-05-08 22:49 UTC, closed without merging