Clarification to Quickstart guide
Boostport/kubernetes-vault pull request #36
Opened 2017-05-05 00:18 UTC by robinpercy

For others that need things spelled out as much as I do :)

2017-05-05 00:23 UTC, F21 requested changes
Looks great! 👍 Just a few small changes 😄

2017-05-05 00:23 UTC, F21 commented on quick-start.md
> +Key             Value
I think the `Handling connection for 8200` line can be removed as it's extraneous. If you run `kubectl port-forward vault-xxxxxxxx 8200` in a separate terminal, it should not be appear in the terminal you are running `vault` commands from.

2017-05-05 00:23 UTC, F21 commented on quick-start.md
Can you add the same example for getting the AppID and adding it to the `sample-app`'s deployment as well?

2017-05-05 12:31 UTC, robinpercy commented on quick-start.md
> +Key             Value
Good point, removed.

2017-05-05 12:32 UTC, robinpercy commented on quick-start.md
yep, done.

2017-05-06 01:18 UTC, F21 commented
Thanks! 👍

2017-05-06 01:18 UTC, F21 approved these changes

2017-05-06 01:18 UTC, merged