Fix comments in setup script for QuickStart
Boostport/kubernetes-vault pull request #72
Opened 2017-08-01 15:25 UTC by tetafro

2017-08-01 22:56 UTC, F21 requested changes
Can you also fix the rest of the numberings under the `Setup Vault` section? I'll push a change to `quick-start.md` to fix the numbering in that document. Once that's done, please squash the commit and we should be good to go! 🚢

2017-08-01 22:56 UTC, F21 commented on deployments/quick-start/setup.sh
>  # Create a Root CA that expires in 10 years:
This should be `2.3`. I got the numbering wrong when writing up `quick-start.md`.

2017-08-01 23:20 UTC, F21 commented
I've fixed the numbering in `quick-start.md` in #73 :smile:

2017-08-02 06:53 UTC, tetafro commented
I've fixed the numbering in setup.sh.

2017-08-02 07:00 UTC, F21 approved these changes

2017-08-02 07:00 UTC, merged

2017-08-02 07:00 UTC, F21 commented
Perfect! Thanks for your contribution!